# Default values for pac-aurora-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
image:
  repository: coco/pac-aurora-backup
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 20Mi
  limits:
    memory: 128Mi


annotations:
  iam.amazonaws.com/role: "K8sPacAuroraBackup"
